mod args;
mod completion;
mod dbus;
mod display;
mod types;

use std::{collections::BTreeMap, process::Stdio};

use args::{Args, CliMode, Commands, ConfigAction, DebugAction, ManagerAction};
use clap::{CommandFactory, Parser};
use dbus::DaemonClient;

use crate::{display::print_devices_pci, types::SystemType};

const BIN_NAME: &str = "cardwire";

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let args = Args::parse();

    // Handle shell completions early before connecting to D-Bus
    if let Commands::Completion { shell } = args.command {
        if shell == clap_complete::Shell::Fish {
            // Use our custom hand-written fish completion script
            print!("{}", completion::FISH_COMPLETIONS);
            return Ok(());
        }

        // Fallback to clap_complete for Bash, Zsh, etc.
        let mut cmd = Args::command();
        let mut buf = Vec::new();
        clap_complete::generate(shell, &mut cmd, BIN_NAME, &mut buf);
        print!(
            "{}",
            String::from_utf8(buf).expect("Invalid utf-8 generated by clap_complete")
        );
        return Ok(());
    }

    // Connect to D-Bus
    let connection: zbus::Connection = match zbus::connection::Builder::system() {
        Ok(builder) => match builder.build().await {
            Ok(conn) => conn,
            Err(e) => handle_error(e),
        },
        Err(e) => handle_error(e),
    };
    let client: DaemonClient<'_> = match DaemonClient::connect(&connection).await {
        Ok(client) => client,
        Err(e) => handle_error(e),
    };

    // Verify the daemon is reachable via Cardwire Manager status before processing args
    if let Err(e) = client.manager_status().await {
        return Err(anyhow::anyhow!(
            "Cannot communicate with cardwired, is the daemon running? - {}",
            e
        ));
    }

    match args.command {
        Commands::Set { mode } => {
            let mode_u32 = match mode {
                CliMode::Integrated => 0,
                CliMode::Hybrid => 1,
                CliMode::Manual => 2,
                CliMode::Smart => 3,
            };

            match client.set_mode(&mode_u32).await {
                Ok(_) => println!("Mode has been set to {}", mode),
                Err(e) => handle_error(e.into()),
            };
        }
        Commands::Get => {
            let available_modes = match client.get_available_modes().await {
                Ok(modes) => modes,
                Err(e) => handle_error(e),
            };
            let available_modes_str = available_modes
                .iter()
                .map(|m| m.to_string().to_lowercase())
                .collect::<Vec<_>>()
                .join(", ");
            match client.get_mode().await {
                Ok(response) => {
                    let response: CliMode = match response {
                        0 => CliMode::Integrated,
                        1 => CliMode::Hybrid,
                        2 => CliMode::Manual,
                        3 => CliMode::Smart,
                        // shouldn't happen
                        _ => CliMode::Manual,
                    };
                    println!("Current Mode: {}", response);
                    println!("Available Mode: {}", available_modes_str);
                }
                Err(e) => handle_error(e),
            };
        }
        Commands::List { full, json } => {
            if full {
                match client.get_pci_device().await {
                    Ok(response) => {
                        print_devices_pci(response)?;
                    }
                    Err(e) => handle_error(e),
                }
            } else {
                let map = get_gpu_list(&client).await;
                if let Err(e) = display::print_devices(map, json) {
                    handle_error(zbus::Error::FDO(Box::new(zbus::fdo::Error::Failed(
                        e.to_string(),
                    ))));
                }
            }
        }
        Commands::Gpu { id, action } => {
            if action.block {
                match client.set_gpu_block(id, true).await {
                    Ok(_) => println!("GPU {} has been blocked", id),
                    Err(e) => handle_error(e.into()),
                };
            } else if action.unblock {
                match client.set_gpu_block(id, false).await {
                    Ok(_) => println!("GPU {} has been unblocked", id),
                    Err(e) => handle_error(e.into()),
                };
            } else if action.lsof {
                match client.lsof(id).await {
                    Ok(map) => {
                        for (path, procs) in map {
                            println!("  {}: {:?}", path, procs);
                        }
                    }
                    Err(e) => handle_error(e),
                };
            } else if action.power {
                match client.get_power_state(id).await {
                    Ok(power_state) => {
                        println!("{}", power_state);
                    }
                    Err(e) => handle_error(e),
                };
            }
        }
        Commands::Config { action } => match action {
            ConfigAction::AutoApplyGpuState { set } => {
                if let Some(val) = set {
                    if let Err(e) = client.set_auto_apply_gpu_state(val).await {
                        handle_error(e.into());
                    } else {
                        println!("AutoApplyGpuState set to {}", val);
                    }
                } else {
                    match client.get_auto_apply_gpu_state().await {
                        Ok(val) => println!("AutoApplyGpuState: {}", val),
                        Err(e) => handle_error(e),
                    }
                }
            }
            ConfigAction::ExperimentalNvidiaBlock { set } => {
                if let Some(val) = set {
                    if let Err(e) = client.set_experimental_nvidia_block(val).await {
                        handle_error(e.into());
                    } else {
                        println!("ExperimentalNvidiaBlock set to {}", val);
                    }
                } else {
                    match client.get_experimental_nvidia_block().await {
                        Ok(val) => println!("ExperimentalNvidiaBlock: {}", val),
                        Err(e) => handle_error(e),
                    }
                }
            }
            ConfigAction::BatteryAutoSwitch { set } => {
                if let Some(val) = set {
                    if let Err(e) = client.set_battery_auto_switch(val).await {
                        handle_error(e.into());
                    } else {
                        println!("BatteryAutoSwitch set to {}", val);
                    }
                } else {
                    match client.get_battery_auto_switch().await {
                        Ok(val) => println!("BatteryAutoSwitch: {}", val),
                        Err(e) => handle_error(e),
                    }
                }
            }
            ConfigAction::BatteryAutoSwitchMode { set } => {
                if let Some(val) = set {
                    {
                        let mode_u32 = match val {
                            CliMode::Integrated => 0,
                            CliMode::Hybrid => 1,
                            CliMode::Manual => 2,
                            CliMode::Smart => 3,
                        };

                        match client.set_battery_auto_switch_mode(&mode_u32).await {
                            Ok(_) => println!("Auto switch mode has been set to {}", val),
                            Err(e) => handle_error(e.into()),
                        };
                    }
                } else {
                    match client.get_battery_auto_switch_mode().await {
                        Ok(response) => {
                            let response: CliMode = match response {
                                0 => CliMode::Integrated,
                                1 => CliMode::Hybrid,
                                2 => CliMode::Manual,
                                3 => CliMode::Smart,
                                // shouldn't happen
                                _ => CliMode::Manual,
                            };
                            println!("BatteryAutoSwitch: {}", response)
                        }
                        Err(e) => handle_error(e),
                    }
                }
            }
            ConfigAction::ExternalDisplayAutoSwitch { set } => {
                if let Some(val) = set {
                    if let Err(e) = client.set_external_display_auto_switch(val).await {
                        handle_error(e.into());
                    } else {
                        println!("ExternalDisplayAutoSwitch set to {}", val);
                    }
                } else {
                    match client.get_external_display_auto_switch().await {
                        Ok(val) => println!("ExternalDisplayAutoSwitch: {}", val),
                        Err(e) => handle_error(e),
                    }
                }
            }
            ConfigAction::Save => {
                if let Err(e) = client.save_to_file().await {
                    handle_error(e);
                } else {
                    println!("Configuration saved");
                }
            }
        },
        Commands::Manager { action } => match action {
            ManagerAction::Status => {
                if let Err(e) = client.manager_status().await {
                    handle_error(e);
                } else {
                    println!("Daemon is alive");
                }
            }
        },
        Commands::Debug { action } => match action {
            DebugAction::DiagnosticGpu => {
                if let Err(e) = client.diagnostic_gpu().await {
                    handle_error(e);
                } else {
                    // TODO: implement debug
                    println!("DiagnosticGpu not implemented yet");
                }
            }
            DebugAction::RefreshGpu => {
                if let Err(e) = client.refresh_gpu().await {
                    handle_error(e);
                } else {
                    println!("GPU list refreshed");
                    match client.get_available_modes().await {
                        Ok(modes) => {
                            let modes_str = modes
                                .iter()
                                .map(|m| m.to_string().to_lowercase())
                                .collect::<Vec<_>>()
                                .join(", ");
                            println!("Available Mode: {}", modes_str);
                        }
                        Err(e) => handle_error(e),
                    }
                }
            }
        },
        Commands::Launch { gpu, program } => {
            let mut available_gpu = get_gpu_list(&client).await;

            available_gpu.retain(|_, gpu| gpu.available);

            let target_gpu = if let Some(gpu_id) = gpu {
                let target = available_gpu.get(&(gpu_id as usize));
                if let Some(gpu) = target
                    && !gpu.launchable
                {
                    let reason = if gpu.blocked {
                        "it is blocked in the current mode"
                    } else {
                        "the daemon reports it as unavailable for launching"
                    };
                    return Err(anyhow::anyhow!(
                        "GPU {} ({}) cannot be launched on: {reason};",
                        gpu.id,
                        gpu.name
                    ));
                }
                target
            // No gpu specified
            } else {
                available_gpu.retain(|_, gpu| gpu.available && gpu.launchable);
                let system_type = SystemType::from_gpulist(&available_gpu);
                match system_type {
                    // 2 GPUs, one iGPU and one dGPU
                    SystemType::Laptop => available_gpu
                        .iter()
                        .find(|(_, gpu)| !gpu.default && gpu.discrete),
                    // 2 GPUs, use default discrete GPU
                    SystemType::Desktop => available_gpu
                        .iter()
                        .find(|(_, gpu)| gpu.default && gpu.discrete),
                    // 1 GPU or 3+ GPUs, get in this priority:
                    // 0. Default Discrete GPU
                    // 1. non-Default discrete GPU
                    // 2. Others
                    SystemType::Manual => available_gpu.iter().max_by_key(|(_, gpu)| {
                        (gpu.default && gpu.discrete, gpu.discrete, gpu.default)
                    }),
                }
                .map(|(_, gpu)| gpu)
            };

            if let Some(gpu) = target_gpu {
                let mut command = std::process::Command::new(&program[0]);

                if program.len() > 1 {
                    command.args(&program[1..]);
                }

                let env = client
                    .get_gpu_env(gpu.id)
                    .await
                    .map_err(|e| anyhow::anyhow!("Failed to get GPU environment: {e}"))?;

                for chunk in env.chunks(2) {
                    if let [key, value] = chunk {
                        command.env(key, value);
                    }
                }
                let status = command
                    .stdout(Stdio::inherit())
                    .stderr(Stdio::inherit())
                    .status()
                    .map_err(|e| {
                        anyhow::anyhow!(
                            "Failed to launch process '{}': {}",
                            program.first().map(String::as_str).unwrap_or("<unknown>"),
                            e
                        )
                    })?;

                match status.code() {
                    Some(code) => std::process::exit(code),
                    None => {
                        return Err(anyhow::anyhow!(
                            "Process was terminated by a signal: {}",
                            status
                        ));
                    }
                };
            } else {
                return Err(anyhow::anyhow!(
                    "No available GPU matched the launch request"
                ));
            }
        }
        Commands::CompleteGpus => {
            let objects = client.get_managed_objects().await.unwrap_or_default();
            for (path, _) in objects {
                let path_str = path.as_str();
                if let Some(id_str) =
                    path_str.strip_prefix("/org/opengamingcollective/cardwire/Gpu/")
                    && let Ok(id) = id_str.parse::<u32>()
                    && let Ok(dbus_dev) = client.get_device(id).await
                {
                    // The \t makes fish show the name as a description next to the ID
                    println!("{}\t{}", id, dbus_dev.name);
                }
            }
        }
        _ => {}
    }

    Ok(())
}

fn handle_error(err: zbus::Error) -> ! {
    match err {
        zbus::Error::MethodError(name, description, _) => {
            if name.as_str() == "org.freedesktop.DBus.Error.ServiceUnknown"
                || name.as_str() == "org.freedesktop.DBus.Error.NameHasNoOwner"
            {
                eprintln!("error: cardwired daemon is not running. Is the service up?");
            } else if let Some(msg) = description {
                eprintln!("{}", msg);
            } else {
                eprintln!("{}", name);
            }
        }
        zbus::Error::FDO(fdo_err) => match &*fdo_err {
            zbus::fdo::Error::AccessDenied(msg)
            | zbus::fdo::Error::Failed(msg)
            | zbus::fdo::Error::InvalidArgs(msg)
            | zbus::fdo::Error::NotSupported(msg) => eprintln!("{}", msg),
            zbus::fdo::Error::ServiceUnknown(_) | zbus::fdo::Error::NameHasNoOwner(_) => {
                eprintln!("error: cardwired daemon is not running. Is the service up?");
            }
            _ => eprintln!("{}", fdo_err),
        },
        _ => eprintln!("{}", err),
    }
    std::process::exit(1)
}

async fn get_gpu_list(client: &'_ DaemonClient<'_>) -> BTreeMap<usize, display::GpuDevice> {
    let mut map: BTreeMap<usize, display::GpuDevice> = BTreeMap::new();
    let objects = match client.get_managed_objects().await {
        Ok(objects) => objects,
        Err(e) => handle_error(e.into()),
    };
    for (path, interfaces) in objects {
        let path_str = path.as_str();
        if let Some(id_str) = path_str.strip_prefix("/org/opengamingcollective/cardwire/Gpu/")
            && let Ok(id) = id_str.parse::<u32>()
        {
            let mut blocked = false;
            let mut launchable = false;
            for (iface, props) in interfaces {
                if iface.as_str() == "org.opengamingcollective.cardwire.Gpu" {
                    if let Some(block_val) = props.get("Block") {
                        blocked = block_val.downcast_ref::<bool>().unwrap_or(false);
                    }
                    if let Some(launchable_val) = props.get("Launchable") {
                        launchable = launchable_val.downcast_ref::<bool>().unwrap_or(false);
                    }
                }
            }
            if let Ok(dbus_dev) = client.get_device(id).await {
                let dev = display::GpuDevice {
                    id,
                    name: dbus_dev.name,
                    pci: dbus_dev.pci,
                    render: dbus_dev.render,
                    card: dbus_dev.card,
                    default: dbus_dev.default,
                    discrete: dbus_dev.discrete,
                    virtual_gpu: dbus_dev.virtual_gpu,
                    available: dbus_dev.available,
                    vendor: dbus_dev.vendor,
                    driver: dbus_dev.driver,
                    blocked,
                    launchable,
                    nvidia: dbus_dev.nvidia,
                    nvidia_minor: dbus_dev.nvidia_minor,
                };
                map.insert(id as usize, dev);
            }
        }
    }
    map
}
